@token = 
@questId = 
@updateId= 
@now = 

### GET REQUESTS
### get quests
GET http://localhost:3000/quest?page=1&limit=6&status=completed&orderBy=foundedDate&sort=desc

### get all my quests
GET http://localhost:3000/quest/own-quests
Content-Type: application/json
Authorization: Bearer {{token}}

### get all my updated quests
GET http://localhost:3000/quest/own-quests-updates
Content-Type: application/json
Authorization: Bearer {{token}}

### get details of a quest
GET http://localhost:3000/quest/{{questId}}
Content-Type: application/json

### POST REQUESTS
### create a quest
POST http://localhost:3000/quest
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "characteristics": ["orejas negras", "mancha blanca en la cabeza"], 
  "direction": "av. siempre viva",
  "gender": "Femenino",
  "health": [],
  "image": "lost.webp",
  "name": "pimienta",
  "race": ["persa", "mestiza"],
  "story": "paseaba con mi gata por el parque al medio día cuando de pronto se perdió en el bosque.",
  "trained": false,
  "type": "Gato",
  "lostDate": "{{now}}",
  "placeOfLost": "en el parque central en el lado oeste"
}

### update a quest
PATCH http://localhost:3000/quest
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{questId}}",
  "characteristics": ["orejas negras", "mancha blanca en la cabeza", "collar rojo"], 
  "direction": "av. siempre viva L-15",
  "gender": "Femenino",
  "health": ["necesita medicación"],
  "name": "luna",
  "race": ["persa", "mestiza"],
  "story": "paseaba con mi gata por el parque al medio día cuando de pronto se perdió en el bosque.",
  "trained": true,
  "lostDate": "2025-06-09T12:35:00Z",
  "foundedDate": "2025-06-09T12:30:00Z",
  "placeOfLost": "en el parque central en el lado oeste por la pileta."
}

### create a update
POST http://localhost:3000/quest/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-06-09T18:30:00Z",
  "description": "vi a una gata acorde a la descripción cerca a la pileta del parque.",
  "place": "parque central en el lado oeste, junto al puesto de venta",
  "quest": "{{questId}}"
}

### upgrade a update
PATCH http://localhost:3000/quest/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{updateId}}",
  "date": "2025-06-09T18:35:00Z",
  "description": "vi a una gata acorde a la descripción cerca a la pileta del parque, no tenía un collar rojo.",
  "place": "parque central en el lado oeste, junto al puesto de venta de globos"
}