@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDBiZmJiZmM0ZDZjZDg4MzQyYWNlOCIsImlhdCI6MTc0OTA3Mzg1MSwiZXhwIjoxNzQ5MTYwMjUxfQ.HYi2rbz872Mz1ajoSI_v1FfSUlAM0NG6IbuYo9R8OgU
@questId = 6840b30dfc4d6cd88342abe8

### GET REQUESTS
### get all the quests
GET http://localhost:3000/quest

### get all my quests
GET http://localhost:3000/quest/own-quests
Content-Type: application/json
Authorization: Bearer {{token}}

### get all my updated quests
GET http://localhost:3000/quest/own-quests-updates
Content-Type: application/json
Authorization: Bearer {{token}}

### get details of a quest
GET http://localhost:3000/quest/{{questId}}
Content-Type: application/json

### POST REQUESTS
### create a quest
POST http://localhost:3000/quest
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "characteristics": ["negra", "valiente"], 
  "direction": "Norte",
  "gender": "Femenino",
  "health": [],
  "image": "founded.webp",
  "name": "Luna",
  "race": ["salchicha", "alemán"],
  "story": "Se perdió en el bosque.",
  "trained": true,
  "type": "Perro",
  "lostDate": "2024-03-10T12:00:00Z",
  "placeOfLost": "Afueras de la ciudad"
}

### create a update
POST http://localhost:3000/quest/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-06-04T18:30:00Z",
  "description": "Vi un salchicha sin correa, parecia perdido en la estación de trenes de la ciudad.",
  "place": "Estación de trenes",
  "quest": "{{questId}}"
}